### ISSUE TITLE
IO handling

### ISSUE THREAD

**Issue by schallerdavid** [openkinome/kinoml#23]
How should we handle reading and writing, e.g. molecules? Would it be good to have an `io` subpackage? Also, loop modeling and system preparation with OE tk will benefit from reading the original pdb file, since openeye uses information stored in the HEADER section. So we would need an OpenEye specific io module.

**Comment by jaimergp** [comment]
Core objects in `kinoml.core` are responsible of importing from several formats. A `kinoml.io` subpackage might be useful to implement more loaders, but those should only be used from `kinoml.core.ObjectModel.from_*` classmethods. 

That's my initial idea, but we might need to revisit how we adapt because there might be edge cases that makes this more difficult than I thought (e.g. lazy loading smiles).
